version: "3.8"

networks:
  converse-test-network:
    driver: bridge

services:
  psql:
    build: ./docker/psql
    image: converse-psql
    container_name: test-converse-psql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    logging:
      driver: none
    networks:
      - converse-test-network

  converse:
    build:
      context: .
      dockerfile: test.Dockerfile
    image: converse-test
    container_name: test-converse
    depends_on:
      - psql
    networks:
      - converse-test-network