version: "3.8"

services:
  psql:
    build: ./docker/psql
    image: converse-psql
    container_name: test-converse-psql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  converse:
    build: ./docker/test.Dockerfile
    image: converse-test
    container_name: test-converse
    depends_on:
      - psql