// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package db

import (
	"github.com/jmoiron/sqlx"
)

// Injectors from wire.go:

func InitializeClient(database *sqlx.DB) (*Client, error) {
	userService := &UserService{
		DB: database,
	}
	client := &Client{
		User: userService,
	}
	return client, nil
}
